[mypy]
python_version = 3.12
strict = True
follow_imports = normal
ignore_missing_imports = False
disallow_any_expr = True
disallow_any_unimported = True
show_error_codes = True
warn_unused_configs = True
