"""Strict installed-package build identity helpers.

The build identity is generated into wheel and source-distribution staging trees.
It binds the exact clean source revision to a digest of every installed package
file except the identity record itself and interpreter-generated bytecode.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Final

BUILD_IDENTITY_SCHEMA: Final = "prob4d.installed-build-identity"
BUILD_IDENTITY_VERSION: Final = 1
BUILD_IDENTITY_FILENAME: Final = "_build_identity.json"
BUILD_IDENTITY_REPOSITORY: Final = "IPS-Stuttgart/Prob4D"

_IDENTITY_FIELDS: Final = frozenset(
    {
        "schema",
        "schema_version",
        "repository",
        "source_revision",
        "source_tree_clean",
        "source_identity_source",
        "package_manifest_sha256",
        "package_file_count",
    }
)
_SOURCE_IDENTITY_SOURCES: Final = frozenset(
    {"git_checkout", "inherited_source_archive", "unavailable"}
)


def _canonical_json(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _sha256_file(path: Path) -> tuple[str, int]:
    before = path.stat()
    digest = hashlib.sha256()
    byte_count = 0
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
            byte_count += len(block)
    after = path.stat()
    identity_before = (before.st_dev, before.st_ino, before.st_size, before.st_mtime_ns)
    identity_after = (after.st_dev, after.st_ino, after.st_size, after.st_mtime_ns)
    if identity_before != identity_after or byte_count != before.st_size:
        raise ValueError(f"package file changed while hashing: {path}")
    return digest.hexdigest(), byte_count


def _require_revision(value: object, *, name: str) -> str:
    if (
        type(value) is not str
        or len(value) not in {40, 64}
        or any(character not in "0123456789abcdef" for character in value)
    ):
        raise ValueError(f"{name} must be an exact lowercase 40- or 64-character Git commit")
    return value


def _require_sha256(value: object, *, name: str) -> str:
    if (
        type(value) is not str
        or len(value) != 64
        or any(character not in "0123456789abcdef" for character in value)
    ):
        raise ValueError(f"{name} must be a lowercase SHA-256 digest")
    return value


def package_manifest(package_root: str | Path) -> tuple[str, int]:
    """Return a deterministic digest and file count for one installed package."""

    root = Path(package_root)
    if not root.is_dir():
        raise ValueError(f"package root does not exist: {root}")

    entries: list[dict[str, object]] = []
    for path in sorted(root.rglob("*"), key=lambda item: item.as_posix()):
        if path.is_symlink():
            raise ValueError(f"package manifest refuses symbolic link: {path}")
        if not path.is_file():
            continue
        relative = path.relative_to(root)
        if relative.as_posix() == BUILD_IDENTITY_FILENAME:
            continue
        if "__pycache__" in relative.parts or path.suffix in {".pyc", ".pyo"}:
            continue
        sha256, byte_count = _sha256_file(path)
        entries.append(
            {
                "path": relative.as_posix(),
                "sha256": sha256,
                "byte_count": byte_count,
            }
        )
    return hashlib.sha256(_canonical_json(entries)).hexdigest(), len(entries)


def build_identity_record(
    package_root: str | Path,
    *,
    source_revision: str | None,
    source_tree_clean: bool,
    source_identity_source: str,
) -> dict[str, object]:
    """Create one strict build-identity record for a staged package tree."""

    if source_revision is not None:
        source_revision = _require_revision(
            source_revision,
            name="source revision",
        )
    if type(source_tree_clean) is not bool:
        raise ValueError("source_tree_clean must be a Boolean")
    if (
        type(source_identity_source) is not str
        or source_identity_source not in _SOURCE_IDENTITY_SOURCES
    ):
        raise ValueError("source_identity_source is unsupported")
    if source_revision is None and source_tree_clean:
        raise ValueError("an unavailable source revision cannot be marked clean")
    if source_identity_source == "unavailable" and source_revision is not None:
        raise ValueError("unavailable source identity cannot carry a revision")

    manifest_sha256, file_count = package_manifest(package_root)
    return {
        "schema": BUILD_IDENTITY_SCHEMA,
        "schema_version": BUILD_IDENTITY_VERSION,
        "repository": BUILD_IDENTITY_REPOSITORY,
        "source_revision": source_revision,
        "source_tree_clean": source_tree_clean,
        "source_identity_source": source_identity_source,
        "package_manifest_sha256": manifest_sha256,
        "package_file_count": file_count,
    }


def validate_build_identity_record(
    value: object,
    *,
    package_root: str | Path,
) -> dict[str, object]:
    """Validate identity semantics and the complete installed package manifest."""

    if not isinstance(value, Mapping) or any(type(key) is not str for key in value):
        raise ValueError("build identity must be a string-keyed mapping")
    missing = _IDENTITY_FIELDS - value.keys()
    unexpected = value.keys() - _IDENTITY_FIELDS
    if missing or unexpected:
        raise ValueError(
            "build identity fields changed; "
            f"missing={sorted(missing)}, unexpected={sorted(unexpected)}"
        )
    if value["schema"] != BUILD_IDENTITY_SCHEMA:
        raise ValueError("build identity schema changed")
    if type(value["schema_version"]) is not int or value["schema_version"] != 1:
        raise ValueError("build identity version changed")
    if value["repository"] != BUILD_IDENTITY_REPOSITORY:
        raise ValueError("build identity repository changed")

    revision_value = value["source_revision"]
    revision = (
        None
        if revision_value is None
        else _require_revision(revision_value, name="build identity source revision")
    )
    clean = value["source_tree_clean"]
    if type(clean) is not bool:
        raise ValueError("build identity source_tree_clean must be a Boolean")
    source = value["source_identity_source"]
    if type(source) is not str or source not in _SOURCE_IDENTITY_SOURCES:
        raise ValueError("build identity source_identity_source is unsupported")
    if revision is None and clean:
        raise ValueError("build identity without a revision cannot be clean")
    if source == "unavailable" and revision is not None:
        raise ValueError("unavailable build identity cannot carry a revision")

    declared_manifest = _require_sha256(
        value["package_manifest_sha256"],
        name="build identity package manifest",
    )
    declared_count = value["package_file_count"]
    if type(declared_count) is not int or declared_count < 0:
        raise ValueError("build identity package_file_count must be a nonnegative integer")
    actual_manifest, actual_count = package_manifest(package_root)
    if actual_manifest != declared_manifest or actual_count != declared_count:
        raise ValueError("installed package bytes do not match the build identity")

    return {
        "schema": BUILD_IDENTITY_SCHEMA,
        "schema_version": BUILD_IDENTITY_VERSION,
        "repository": BUILD_IDENTITY_REPOSITORY,
        "source_revision": revision,
        "source_tree_clean": clean,
        "source_identity_source": source,
        "package_manifest_sha256": declared_manifest,
        "package_file_count": declared_count,
    }


def load_build_identity(
    path: str | Path,
    *,
    package_root: str | Path | None = None,
) -> dict[str, object]:
    """Load one identity using duplicate-key and finite-JSON validation."""

    identity_path = Path(path)

    def reject_duplicate(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
        result: dict[str, Any] = {}
        for key, item in pairs:
            if key in result:
                raise ValueError(f"duplicate build identity key: {key}")
            result[key] = item
        return result

    def reject_nonfinite(token: str) -> None:
        raise ValueError(f"non-finite build identity value: {token}")

    try:
        value = json.loads(
            identity_path.read_text(encoding="utf-8"),
            object_pairs_hook=reject_duplicate,
            parse_constant=reject_nonfinite,
        )
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        raise ValueError("cannot read installed build identity") from error
    return validate_build_identity_record(
        value,
        package_root=(identity_path.parent if package_root is None else package_root),
    )


def write_build_identity(
    path: str | Path,
    *,
    package_root: str | Path,
    source_revision: str | None,
    source_tree_clean: bool,
    source_identity_source: str,
) -> dict[str, object]:
    """Write a canonical build identity into a staging package tree."""

    record = build_identity_record(
        package_root,
        source_revision=source_revision,
        source_tree_clean=source_tree_clean,
        source_identity_source=source_identity_source,
    )
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(record, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    return record


__all__ = [
    "BUILD_IDENTITY_FILENAME",
    "BUILD_IDENTITY_REPOSITORY",
    "BUILD_IDENTITY_SCHEMA",
    "BUILD_IDENTITY_VERSION",
    "build_identity_record",
    "load_build_identity",
    "package_manifest",
    "validate_build_identity_record",
    "write_build_identity",
]
