"""Linear task-state closure for recursive posterior-preserving compression.

This module does not claim that functional observers or invariant state
subspaces are new.  It exposes the smallest row space generated by a registered
linear task, the observation map, and repeated dynamics pullback.  On that
closed task state, the existing posterior-preserving shared-noise compressor can
be applied at every Gaussian update; exact one-step task-state posterior parity
then propagates by induction.

The closure is intentionally strict.  If task-relevant dynamics or observation
rows require the complete state, the returned basis grows to the complete state
rather than silently discarding those directions.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

Array = NDArray[np.float64]


def _array(value: object, name: str) -> Array:
    raw = np.asarray(value)
    if np.iscomplexobj(raw):
        raise ValueError(f"{name} must be real")
    result = np.asarray(raw, dtype=np.float64)
    if not np.all(np.isfinite(result)):
        raise ValueError(f"{name} must be finite")
    return result


def _relative_tolerance(value: object) -> float:
    if isinstance(value, (bool, np.bool_)) or not isinstance(
        value, (int, float, np.integer, np.floating)
    ):
        raise TypeError("rank_relative_tolerance must be a real scalar")
    result = float(value)
    if not np.isfinite(result) or not 0.0 <= result < 1.0:
        raise ValueError("rank_relative_tolerance must lie in [0, 1)")
    return result


def _readonly(value: Array) -> Array:
    result = np.array(value, dtype=np.float64, copy=True)
    result.setflags(write=False)
    return result


def _row_basis(value: Array, relative_tolerance: float) -> Array:
    """Return a deterministic orthonormal basis for the supplied row space."""
    if value.ndim != 2:
        raise ValueError("row-space input must be a matrix")
    if value.shape[0] == 0:
        return np.empty((0, value.shape[1]), dtype=np.float64)
    _, singular, right = np.linalg.svd(value, full_matrices=False)
    if not singular.size or singular[0] == 0.0:
        return np.empty((0, value.shape[1]), dtype=np.float64)
    rank = int(np.count_nonzero(singular > relative_tolerance * singular[0]))
    basis = right[:rank].copy()
    for row in range(rank):
        pivot = int(np.argmax(np.abs(basis[row])))
        if basis[row, pivot] < 0.0:
            basis[row] *= -1.0
    return basis


def _relative_residual(value: Array, reconstructed: Array) -> float:
    scale = max(float(np.linalg.norm(value, ord="fro")), 1.0)
    return float(np.linalg.norm(value - reconstructed, ord="fro")) / scale


@dataclass(frozen=True, slots=True)
class RecursiveTaskClosure:
    """Audited finite-dimensional task state for an LTI Gaussian model.

    For ``z = basis @ x`` the returned maps satisfy, up to numerical tolerance,

    ``task_matrix @ x = task_map @ z``
    ``observation_matrix @ x = observation_map @ z``
    ``basis @ F @ x = transition_map @ z``.

    Hence a linear-Gaussian model whose process and measurement noises are
    exogenous can be filtered recursively in ``z`` without reconstructing the
    discarded state directions.  This object supplies the task-state closure;
    posterior-preserving compression of a correlated measurement-noise factor is
    a separate operation.
    """

    basis: Array
    task_map: Array
    observation_map: Array
    transition_map: Array
    iterations: int
    task_residual: float
    observation_residual: float
    transition_residual: float

    def __post_init__(self) -> None:
        for name in ("basis", "task_map", "observation_map", "transition_map"):
            object.__setattr__(self, name, _readonly(getattr(self, name)))

    @property
    def state_dimension(self) -> int:
        return int(self.basis.shape[1])

    @property
    def closure_dimension(self) -> int:
        return int(self.basis.shape[0])

    def summary(self) -> dict[str, object]:
        return {
            "state_dimension": self.state_dimension,
            "closure_dimension": self.closure_dimension,
            "iterations": self.iterations,
            "task_residual": self.task_residual,
            "observation_residual": self.observation_residual,
            "transition_residual": self.transition_residual,
            "claim_boundary": (
                "linear-time-invariant-task-state-closure; functional-observer "
                "lineage is prior work"
            ),
        }


def recursive_linear_task_closure(
    state_transition: object,
    *,
    task_matrix: object,
    observation_matrix: object,
    rank_relative_tolerance: float = 1e-12,
) -> RecursiveTaskClosure:
    """Construct the minimum row space closed under the registered LTI model.

    Starting from the row span of the task and observation matrices, repeatedly
    add the dynamics pullback ``B @ F``.  Because the state is finite
    dimensional, the exact construction stabilizes in at most ``n`` rank
    increases.  The returned orthonormal rows span the smallest subspace that
    contains the registered rows and is right-invariant under ``F``.

    Including observation rows is deliberate: without it, a one-step query can
    be exact while later measurements reintroduce discarded nuisance-state
    information.  If this strict closure becomes full-state, the function
    reports that fact rather than manufacturing a smaller recursive claim.
    """
    transition = _array(state_transition, "state_transition")
    if (
        transition.ndim != 2
        or transition.shape[0] < 1
        or transition.shape[0] != transition.shape[1]
    ):
        raise ValueError("state_transition must be a nonempty square matrix")
    dimension = transition.shape[0]
    task = _array(task_matrix, "task_matrix")
    observation = _array(observation_matrix, "observation_matrix")
    if task.ndim != 2 or task.shape[0] < 1 or task.shape[1] != dimension:
        raise ValueError("task_matrix must have shape (Q, state_dimension), Q > 0")
    if observation.ndim != 2 or observation.shape[1] != dimension:
        raise ValueError("observation_matrix must have shape (M, state_dimension)")
    tolerance = _relative_tolerance(rank_relative_tolerance)

    basis = _row_basis(np.vstack((task, observation)), tolerance)
    iterations = 0
    for _ in range(dimension):
        candidate = _row_basis(np.vstack((basis, basis @ transition)), tolerance)
        iterations += 1
        if candidate.shape[0] == basis.shape[0]:
            basis = candidate
            break
        basis = candidate
    else:  # pragma: no cover - dimension argument makes this unreachable in exact rank arithmetic.
        raise RuntimeError("task closure did not stabilize within the state dimension")

    task_map = task @ basis.T
    observation_map = observation @ basis.T
    transition_map = basis @ transition @ basis.T
    task_residual = _relative_residual(task, task_map @ basis)
    observation_residual = _relative_residual(observation, observation_map @ basis)
    transition_residual = _relative_residual(basis @ transition, transition_map @ basis)
    audit_limit = max(1e-10, 100.0 * tolerance)
    if max(task_residual, observation_residual, transition_residual) > audit_limit:
        raise ValueError("numerical task closure failed its reconstruction audit")

    return RecursiveTaskClosure(
        basis=basis,
        task_map=task_map,
        observation_map=observation_map,
        transition_map=transition_map,
        iterations=iterations,
        task_residual=task_residual,
        observation_residual=observation_residual,
        transition_residual=transition_residual,
    )
